### ISSUE TITLE
ASK queries are not supported

### ISSUE THREAD

**Issue by JervenBolleman** [calipho-sib/sparql-playground#2]
```ASK {FILTER(2>1)}``` does not work

**Comment by ddtxra** [comment]
Hello Jerven,
In fact, it only supports SELECT so far.
ASK can easily be added on SesameRepository java class by adding a new method:

```java
public boolean ask(String sparqlAskQuery) {
   BooleanQuery bq = conn.prepareBooleanQuery(QueryLanguage.SPARQL, sparqlAskQuery);
   return bq.evaluate();
}
```
It may be necessary to adapt the SNORQL interface as well, since AFAIK SNORQL doesn't know how to handle ASK queries responses by default. dbpedia has the same issue: http://dbpedia.org/snorql/?query=ASK+%7BFILTER%282%3E1%29%7D

**Comment by JervenBolleman** [comment]
Same for CONSTRUCT queries. I will have a look at it and see if it can be done, correctly.

**Comment by ddtxra** [comment]
ASK queries are now supported from version 1.4.0.
